// shop-web-next/src/app/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card } from '@/components/ui/card'
import { useAuthStore } from '@/lib/stores/auth'

export default function LoginPage() {
  const router = useRouter()
  const login = useAuthStore(state => state.login)
  
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    
    if (!username || !password) {
      setError('请输入用户名和密码')
      return
    }

    setIsLoading(true)
    
    try {
      const success = await login(username, password)
      
      if (success) {
        router.push('/')
      } else {
        setError('登录失败，请检查用户名和密码')
      }
    } catch {
      setError('登录失败，请稍后再试')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-pink-50 via-white to-orange-50 p-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-md"
      >
        <Card className="p-8 backdrop-blur-sm bg-white/80 shadow-2xl border-0">
          <motion.div
            initial={{ scale: 0.9 }}
            animate={{ scale: 1 }}
            transition={{ delay: 0.2, duration: 0.3 }}
            className="text-center mb-8"
          >
            <h1 className="text-4xl font-bold bg-gradient-to-r from-pink-500 to-orange-500 bg-clip-text text-transparent mb-2">
              YQSX 智能零食商城
            </h1>
            <p className="text-gray-600">AI 驱动的智能购物体验</p>
          </motion.div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="username">用户名</Label>
              <Input
                id="username"
                type="text"
                placeholder="请输入用户名"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="transition-all focus:ring-2 focus:ring-primary"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">密码</Label>
              <Input
                id="password"
                type="password"
                placeholder="请输入密码"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="transition-all focus:ring-2 focus:ring-primary"
              />
            </div>

            {error && (
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                className="text-sm text-red-500 bg-red-50 p-3 rounded-md"
              >
                {error}
              </motion.div>
            )}

            <Button
              type="submit"
              disabled={isLoading}
              className="w-full h-12 text-base font-semibold bg-gradient-to-r from-pink-500 to-orange-500 hover:from-pink-600 hover:to-orange-600 transition-all duration-300"
            >
              {isLoading ? '登录中...' : '登录'}
            </Button>
          </form>

          <div className="mt-6 text-center text-sm text-gray-500">
            <p>测试账号：admin / 123456</p>
          </div>
        </Card>
      </motion.div>
    </div>
  )
}

// shop-web/src/views/login/index.vue
<template>
  <div class="login-page">
    <div class="login-container glass-card">
      <div class="login-header">
        <h1 class="login-title gradient-text">YQSX智能零食商城</h1>
        <p class="login-subtitle">AI识别 · 智能推荐 · 轻松购物</p>
      </div>

      <el-form
        ref="formRef"
        :model="formData"
        :rules="rules"
        class="login-form"
        size="large"
      >
        <el-form-item prop="username">
          <el-input
            v-model="formData.username"
            placeholder="请输入用户名"
            prefix-icon="User"
            clearable
          />
        </el-form-item>

        <el-form-item prop="password">
          <el-input
            v-model="formData.password"
            type="password"
            placeholder="请输入密码"
            prefix-icon="Lock"
            show-password
            @keyup.enter="handleLogin"
          />
        </el-form-item>

        <el-form-item>
          <el-button
            type="primary"
            class="login-btn"
            :loading="loading"
            @click="handleLogin"
          >
            {{ loading ? '登录中...' : '登录' }}
          </el-button>
        </el-form-item>
      </el-form>

      <div class="login-tips">
        <p>测试账号：admin / 123456</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import type { FormInstance, FormRules } from 'element-plus'

const router = useRouter()
const authStore = useAuthStore()

const formRef = ref<FormInstance>()
const loading = ref(false)

const formData = reactive({
  username: '',
  password: ''
})

const rules: FormRules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码长度不能少于6位', trigger: 'blur' }
  ]
}

const handleLogin = async () => {
  if (!formRef.value) return
  
  try {
    await formRef.value.validate()
    loading.value = true
    
    const success = await authStore.login(formData.username, formData.password)
    
    if (success) {
      router.push('/')
    }
  } catch (error) {
    console.error('表单验证失败:', error)
  } finally {
    loading.value = false
  }
}
</script>

<style lang="scss" scoped>
@import '@/assets/styles/variables.scss';

.login-page {
  width: 100%;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: $spacing-3;
}

.login-container {
  width: 100%;
  max-width: 420px;
  padding: $spacing-5;
  animation: scaleIn $duration-base $easing-ease-out;
}

.login-header {
  text-align: center;
  margin-bottom: $spacing-4;
}

.login-title {
  font-size: $font-size-3xl;
  font-weight: bold;
  margin-bottom: $spacing-2;
}

.login-subtitle {
  color: $text-secondary;
  font-size: $font-size-sm;
}

.login-form {
  margin-top: $spacing-4;

  :deep(.el-input__wrapper) {
    border-radius: $radius-base;
    box-shadow: $shadow-sm;
    transition: all $duration-base $easing-ease-in-out;

    &:hover {
      box-shadow: $shadow-md;
    }
  }
}

.login-btn {
  width: 100%;
  height: 48px;
  font-size: $font-size-lg;
  font-weight: 600;
  border-radius: $radius-base;
  background: $primary-gradient;
  border: none;
  transition: all $duration-base $easing-ease-in-out;

  &:hover {
    transform: translateY(-2px);
    box-shadow: $shadow-lg;
  }

  &:active {
    transform: scale(0.98);
  }
}

.login-tips {
  text-align: center;
  margin-top: $spacing-3;
  
  p {
    color: $text-tertiary;
    font-size: $font-size-sm;
  }
}
</style>
